spring.application.name=fleet

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/fleet}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.jpa.hibernate.ddl-auto=none