-- liquibase formatted sql

-- changeset xqsy:2026-08-13-create-vehicle-types
CREATE TABLE vehicle_types
(
    code varchar(30) primary key
);

INSERT INTO vehicle_types (code)
VALUES ('TRUCK'), ('BUS');

-- changeset xqsy:2026-08-13-create-vehicle-conditions
CREATE TABLE vehicle_conditions
(
    code varchar(30) primary key
);

INSERT INTO vehicle_conditions (code)
VALUES ('GOOD'), ('NEEDS_REPAIR');

-- changeset xqsy:2026-08-13-create-transport-request-statuses
CREATE TABLE transport_request_statuses
(
    code varchar(30) PRIMARY KEY
);

INSERT INTO transport_request_statuses (code)
VALUES
    ('NEW'),
    ('ASSIGNED'),
    ('IN_PROGRESS'),
    ('COMPLETED'),
    ('CANCELLED');

-- changeset xqsy:2026-08-13-create-vehicles
CREATE TABLE vehicles
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_number varchar(30) not null unique check (trim(registration_number) <> ''),
    vehicle_type varchar(30) not null,
    load_capacity_kg integer not null default 0 check (load_capacity_kg >= 0),
    passenger_capacity integer not null default 0 check (passenger_capacity >= 0),
    condition varchar(30) not null,

    constraint fk_vehicles_vehicle_type
        foreign key (vehicle_type)
            references vehicle_types(code),

    constraint fk_vehicles_condition
        foreign key (condition)
            references vehicle_conditions(code)
);

-- changeset xqsy:2026-08-13-create-drivers
CREATE TABLE drivers
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(50) not null check (trim(first_name) <> ''),
    last_name varchar(50) not null check (trim(last_name) <> ''),
    license_number varchar(30) not null unique check (trim(license_number) <> ''),
    vehicle_id bigint unique,
    active boolean not null default true,

    constraint fk_drivers_vehicle
        foreign key (vehicle_id)
            references vehicles (id)
            on delete set null,

    constraint uq_drivers_id_vehicle unique (id, vehicle_id)
);

-- changeset xqsy:2026-08-13-create-transport-requests
CREATE TABLE transport_requests
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    departure_address varchar(250) not null check (trim(departure_address) <> ''),
    destination_address varchar(250) not null check (trim(destination_address) <> ''),
    required_vehicle_type varchar(30) not null,
    cargo_weight_kg integer not null default 0 check (cargo_weight_kg >= 0),
    passenger_count integer not null default 0 check (passenger_count >= 0),
    description text,
    request_status varchar(30) not null,
    created_at timestamptz not null default current_timestamp,

    constraint fk_transport_requests_vehicle_type
        foreign key (required_vehicle_type)
            references vehicle_types(code),

    constraint fk_transport_requests_status
        foreign key (request_status)
            references transport_request_statuses(code)
);

-- changeset xqsy:2026-08-13-create-trips
CREATE TABLE trips
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id bigint not null unique,
    driver_id bigint not null,
    vehicle_id bigint not null,
    started_at timestamptz,
    completed_at timestamptz,
    completion_comment text,
    vehicle_condition_after varchar(20),

    constraint fk_trips_request
        foreign key (request_id)
            references transport_requests (id),

    constraint fk_trips_vehicle
        foreign key (vehicle_id)
            references vehicles (id),

    constraint fk_trips_driver_vehicle
        foreign key (driver_id, vehicle_id)
            references drivers (id, vehicle_id),

    constraint fk_trips_vehicle_condition
        foreign key (vehicle_condition_after)
            references vehicle_conditions(code)
);

-- changeset xqsy:2026-08-13-create-fk-indices-for-trips
CREATE INDEX idx_trips_driver_id ON trips(driver_id);

CREATE INDEX idx_trips_vehicle_id ON trips(vehicle_id);
