-- liquibase formatted sql

-- changeset xqsy:2026-09-11-single-table
CREATE TABLE st_vehicles
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_number varchar(30) not null unique,
    vehicle_type varchar(30) not null,
    vehicle_condition varchar(30) not null,

    load_capacity_kg integer check (load_capacity_kg >= 0),
    passenger_capacity integer check (passenger_capacity >= 0),

    constraint fk_vehicles_vehicle_condition
        foreign key (vehicle_condition)
            references vehicle_conditions(code)
);

-- changeset xqsy:2026-09-11-joined
CREATE TABLE j_vehicles
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_number varchar(30) not null unique,
    vehicle_condition varchar(30) not null,

    constraint fk_j_vehicles_vehicle_condition
        foreign key (vehicle_condition)
            references vehicle_conditions(code)
);

CREATE TABLE j_trucks
(
    id BIGINT PRIMARY KEY,
    load_capacity_kg integer check (load_capacity_kg >= 0),

    constraint fk_trucks_vehicle
        foreign key (id)
            references j_vehicles(id)
            on delete cascade
);

CREATE TABLE j_buses
(
    id BIGINT PRIMARY KEY,
    passenger_capacity integer check (passenger_capacity >= 0),

    constraint fk_buses_vehicle
        foreign key (id)
            references j_vehicles(id)
            on delete cascade
);

-- changeset xqsy:2026-09-11-table-per-class
CREATE SEQUENCE vehicle_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE tpc_trucks
(
    id BIGINT PRIMARY KEY,
    registration_number varchar(30) not null unique,
    vehicle_condition varchar(30) not null,
    load_capacity_kg integer check (load_capacity_kg >= 0),

    constraint fk_tpc_truck_vehicle_condition
        foreign key (vehicle_condition)
            references vehicle_conditions(code)
);

CREATE TABLE tpc_buses
(
    id BIGINT PRIMARY KEY,
    registration_number varchar(30) not null unique,
    vehicle_condition varchar(30) not null,
    passenger_capacity integer check (passenger_capacity >= 0),

    constraint fk_tpc_bus_vehicle_condition
        foreign key (vehicle_condition)
            references vehicle_conditions(code)
);