spring.application.name=trip-cost-service

server.port=8081

spring.mongodb.uri=mongodb://${MONGO_USER:mongo}:${MONGO_PASSWORD:mongo}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:trip-costs}?authSource=admin

trip-cost.fuel-consumption-per-km=0.12
trip-cost.fuel-price-per-liter=1.70